<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>quadruped_integration_tests</name>
  <version>0.0.0</version>
  <description>Ingration tests for quadruped_ros2</description>
  <maintainer email="roboticarts1@gmail.com">Robert Vasquez Zavaleta</maintainer>
  <license>GPL-3.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <test_depend>launch_testing</test_depend>
  <test_depend>pytest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
